export type ProjectLink = {
  label: string
  href: string
}

export type Project = {
  slug: string
  title: string
  subtitle: string
  summary: string
  problem: string
  approach: string
  impact: string
  tags: string[]
  links: ProjectLink[]
  inProgress?: boolean
}

export const projects: Project[] = [
  {
    slug: 'omni-retail-ai',
    title: 'OmniRetail AI — Multimodal Marketing Copilot',
    subtitle: 'Flagship · Deployed full-stack ML product',
    summary:
      'An AI marketing copilot that turns raw retail data into ranked, inventory-aware campaign recommendations with RAG-grounded ad copy — live and clickable.',
    problem:
      'Retail marketing teams manage thousands of products across many customer segments, but campaign planning rarely scales with the catalog: promotions are not tied to real purchase likelihood or inventory, and segments exist as concepts without an operational targeting workflow.',
    approach:
      'Built the full pipeline: KMeans segmentation over RFM-style behavioral features (5 segments), an XGBoost purchase-intent model scoring every customer-product pair, and an inventory-aware ranking layer that diversifies across promotion strategies. Ad copy is generated by Claude, grounded through a FAISS retrieval index over the product catalog so copy reflects real product context. Served via a FastAPI backend and a React 19 + TanStack frontend, deployed on Cloudflare Workers and Railway.',
    impact:
      'Purchase-intent model reaches ROC-AUC 0.93 on the held-out test set, with every metric reproducible from the repo’s own evaluation pipeline. The result is a working decision tool — pick a segment, see ranked product picks with explanations, generate grounded ad copy, export to CSV.',
    tags: ['Python', 'XGBoost', 'RAG', 'FAISS', 'Claude API', 'FastAPI', 'React', 'Deployment'],
    links: [
      { label: 'Live demo', href: 'https://tanstack-start-app.letitiachang0807-bb0.workers.dev/overview' },
      { label: 'GitHub', href: 'https://github.com/Letitia-Chang/omni-retail-ai' },
    ],
  },
  {
    slug: 'cerm',
    title: 'CERM — Community Evacuation Resource Matcher',
    subtitle: 'WiDS Datathon 2026 · Georgia Tech',
    summary:
      'A decision-support web app that matches people offering evacuation help with the wildfire-threatened census tracts that need it most.',
    problem:
      'Existing wildfire tools focus on fire prediction and monitoring, not real-time coordination of assistance — leaving elderly residents, people with disabilities, and households without vehicle access under-supported during evacuations.',
    approach:
      'Combined ACS demographic vulnerability data, live request signals, and geographic proximity into a weighted matching engine that ranks census tracts for each helper. An LLM extracts structured tags from free-text requests (with a rule-based fallback), an interactive Leaflet map color-codes need across three California counties, and a fire-aware safety constraint excludes active fire zones from matching entirely, redirecting residents to 911.',
    impact:
      'Delivered a live, working prototype validated with a backtest against the 2018 Camp Fire using official CAL FIRE perimeter data. Designed as decision support rather than automated dispatch — surfacing where help is needed while protecting requester privacy.',
    tags: ['Python', 'Geospatial Data', 'LLM Tagging', 'Decision Support', 'Social Impact'],
    links: [
      { label: 'Live demo', href: 'https://letitia-chang.github.io/cerm-wildfire-evacuation-tool/' },
      { label: 'GitHub', href: 'https://github.com/Letitia-Chang/cerm-wildfire-evacuation-tool' },
    ],
  },
  {
    slug: 'telco-churn',
    title: 'Customer Churn Prediction',
    subtitle: 'End-to-end applied ML project',
    summary:
      'A full churn-prediction pipeline on a real telco dataset — from raw data to a tuned model with business-ready retention insights.',
    problem:
      'A telecom provider needs to know which customers are at risk of churning and which levers (contract type, tenure, service add-ons) actually move the needle — not a black-box score with no explanation.',
    approach:
      'Cleaned and explored 7,000+ customer records, engineered features from tenure, billing, and service usage, then trained and compared Logistic Regression, Decision Tree, and XGBoost classifiers — tuning XGBoost with RandomizedSearchCV and analyzing feature importance to explain what drives churn.',
    impact:
      'Reached ~80% accuracy with clear precision/recall tradeoffs, and translated the top churn drivers into concrete retention recommendations around contract incentives and onboarding.',
    tags: ['Python', 'scikit-learn', 'XGBoost', 'Classification', 'EDA'],
    links: [
      { label: 'GitHub', href: 'https://github.com/Letitia-Chang/customer-churn-prediction' },
    ],
  },
  {
    slug: 'substrate',
    title: 'Substrate — Grid-Relief Scoring Console',
    subtitle: 'Cox "Play With Purpose" Hackathon 2026 · Decarbonization track',
    summary:
      'A data-driven console that scores and ranks commercial buildings by how much peak electrical capacity a retrofit frees per dollar invested.',
    problem:
      'Utilities and cities want to prioritize building retrofits for decarbonization, but lack a way to compare thousands of candidate buildings on actual grid impact per dollar — so retrofit investment is allocated by intuition rather than evidence.',
    approach:
      'Built a scoring model that ranks commercial buildings by electrical capacity freed at peak hours per retrofit dollar, and shaped it into a judged product pitch — elevator pitch, live demo, and judge Q&A — with a cross-functional team inside the hackathon window.',
    impact:
      'Completed, submitted, and demoed live to judges — turning an ambiguous decarbonization brief into a concrete, defensible prioritization tool under time pressure.',
    tags: ['Analytics', 'Metric Design', 'Sustainability', 'Product Thinking', 'Hackathon'],
    links: [
      { label: 'Live demo', href: 'https://substrate.madewithremy.com/' },
    ],
  },
  {
    slug: 'bird-migration',
    title: 'Bird Migration Network Explorer',
    subtitle: 'Data & visual analytics project',
    summary:
      'An interactive visual analytics tool for exploring North American bird migration patterns as networks that shift by species, season, and year.',
    problem:
      'Millions of bird sighting records exist, but raw observation data makes it hard to see the structure of migration — how routes connect regions, and how those networks change across months and years.',
    approach:
      'Building migration networks from sighting data for four species (Ruby-throated Hummingbird, Swainson’s Thrush, Magnolia Warbler, Song Sparrow), served from a FastAPI + PostgreSQL backend with precomputed network snapshots per species and year, and rendered as an interactive map-based React frontend with tunable network parameters.',
    impact:
      'In progress — core backend, network computation, and interactive frontend are working; currently tuning network construction parameters and visualization design.',
    tags: ['Python', 'FastAPI', 'PostgreSQL', 'Network Analysis', 'React', 'Visualization'],
    links: [],
    inProgress: true,
  },
  {
    slug: 'content-generation-agent',
    title: 'Content Generation Agent',
    subtitle: 'Multi-step LLM pipeline · North Star AI Labs',
    summary:
      'A multi-step LLM content pipeline that takes raw intake to publish-ready, brand-voiced articles with a human review gate — the deployable twin of a production system shipped during my internship.',
    problem:
      'Content teams doing research-driven publishing repeat the same manual loop — gather sources, find an angle, draft, edit for brand voice, repurpose per channel — and ad-hoc LLM use produces inconsistent, off-brand output with no review workflow.',
    approach:
      'Building a staged pipeline — intake → normalize → strategize (angle) → draft → brand-voice edit → human review → repurpose → export — where each step is a separate, testable Claude API call with structured state in Supabase/Postgres, a React + TypeScript review UI, and serverless AI endpoints on Vercel.',
    impact:
      'In progress — mirrors the production article-generation system I built at North Star AI Labs (multi-source intake converging into a published feed), rebuilt as a self-contained, demoable product.',
    tags: ['LLM Pipeline', 'Claude API', 'Agents', 'Supabase', 'TypeScript', 'React'],
    links: [],
    inProgress: true,
  },
]
